//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.7.0.0 (NJsonSchema v11.6.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

import { ApiClientBase } from "@/api/apiClientBase";
import { ApiResponse } from "@/api/apiResponse";
import {
    CategoryRef,
    ConsumptionLogRef,
    ProductRef,
    StorageLocationRef,
    TrackedProductRef
} from "@/models/types";import axios, { AxiosError } from 'axios';
import type { AxiosInstance, AxiosRequestConfig, AxiosResponse, CancelToken } from 'axios';

export class CategoriesClient extends ApiClientBase {
    protected instance: AxiosInstance;
    protected baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, instance?: AxiosInstance) {

        super();

        this.instance = instance || axios.create();

        this.baseUrl = baseUrl ?? "http://localhost:5095/";

    }

    static operations = {

        categoriesGET: "api/v1/Categories/{id}",
        categoriesDELETE: "api/v1/Categories/{id}",
        categoriesAll: "api/v1/Categories",
        categoriesPOST: "api/v1/Categories",
        categoriesPUT: "api/v1/Categories",
    }

    static operationParams = {

        categoriesGET: {} as {
            id: CategoryRef;
        },

        categoriesDELETE: {} as {
            id: CategoryRef;
        },

        categoriesAll: {} as {
        },

        categoriesPOST: {} as {
            body: Partial<CreateCategoryRequest>;
        },

        categoriesPUT: {} as {
            body: Partial<UpdateCategoryRequest>;
        },
    }

    /**
     * @return OK
     */
    categoriesGET(id: CategoryRef, cancelToken?: CancelToken): Promise<ApiResponse<CategoryDto>> {
        let url_ = this.baseUrl + "/api/v1/Categories/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace(/{id}/gi, encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.instance.request(transformedOptions_);
        }).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processCategoriesGET(_response);
        });
    }

    protected processCategoriesGET(response: AxiosResponse): Promise<ApiResponse<CategoryDto>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = typeof(resultData200) === "object" ? resultData200 : JSON.parse(resultData200);
            return Promise.resolve<ApiResponse<CategoryDto>>(new ApiResponse<CategoryDto>(status, _headers, result200));

        } else if (status === 404) {
            return throwException("NotFound: " + response.config.url, status, response.data, _headers, null);
        }
        else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<CategoryDto>>(new ApiResponse(status, _headers, null as any));
    }

    /**
     * @return OK
     */
    categoriesDELETE(id: CategoryRef, cancelToken?: CancelToken): Promise<ApiResponse<void>> {
        let url_ = this.baseUrl + "/api/v1/Categories/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace(/{id}/gi, encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "DELETE",
            url: url_,
            headers: {
            },
            cancelToken
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.instance.request(transformedOptions_);
        }).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processCategoriesDELETE(_response);
        });
    }

    protected processCategoriesDELETE(response: AxiosResponse): Promise<ApiResponse<void>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            return Promise.resolve<ApiResponse<void>>(new ApiResponse<void>(status, _headers, null as any));

        } else if (status === 404) {
            return throwException("NotFound: " + response.config.url, status, response.data, _headers, null);
        }
        else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<void>>(new ApiResponse(status, _headers, null as any));
    }

    /**
     * @return OK
     */
    categoriesAll( cancelToken?: CancelToken): Promise<ApiResponse<CategoryDto[]>> {
        let url_ = this.baseUrl + "/api/v1/Categories";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.instance.request(transformedOptions_);
        }).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processCategoriesAll(_response);
        });
    }

    protected processCategoriesAll(response: AxiosResponse): Promise<ApiResponse<CategoryDto[]>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = typeof(resultData200) === "object" ? resultData200 : JSON.parse(resultData200);
            return Promise.resolve<ApiResponse<CategoryDto[]>>(new ApiResponse<CategoryDto[]>(status, _headers, result200));

        } else if (status === 404) {
            return throwException("NotFound: " + response.config.url, status, response.data, _headers, null);
        }
        else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<CategoryDto[]>>(new ApiResponse(status, _headers, null as any));
    }

    /**
     * @return OK
     */
    categoriesPOST(body: CreateCategoryRequest, cancelToken?: CancelToken): Promise<ApiResponse<CreatedEntityDtoOfintAndCategoryRef>> {
        let url_ = this.baseUrl + "/api/v1/Categories";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.instance.request(transformedOptions_);
        }).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processCategoriesPOST(_response);
        });
    }

    protected processCategoriesPOST(response: AxiosResponse): Promise<ApiResponse<CreatedEntityDtoOfintAndCategoryRef>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = typeof(resultData200) === "object" ? resultData200 : JSON.parse(resultData200);
            return Promise.resolve<ApiResponse<CreatedEntityDtoOfintAndCategoryRef>>(new ApiResponse<CreatedEntityDtoOfintAndCategoryRef>(status, _headers, result200));

        } else if (status === 404) {
            return throwException("NotFound: " + response.config.url, status, response.data, _headers, null);
        }
        else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<CreatedEntityDtoOfintAndCategoryRef>>(new ApiResponse(status, _headers, null as any));
    }

    /**
     * @return OK
     */
    categoriesPUT(body: UpdateCategoryRequest, cancelToken?: CancelToken): Promise<ApiResponse<UpdatedEntityDtoOfintAndCategoryRef>> {
        let url_ = this.baseUrl + "/api/v1/Categories";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "PUT",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.instance.request(transformedOptions_);
        }).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processCategoriesPUT(_response);
        });
    }

    protected processCategoriesPUT(response: AxiosResponse): Promise<ApiResponse<UpdatedEntityDtoOfintAndCategoryRef>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = typeof(resultData200) === "object" ? resultData200 : JSON.parse(resultData200);
            return Promise.resolve<ApiResponse<UpdatedEntityDtoOfintAndCategoryRef>>(new ApiResponse<UpdatedEntityDtoOfintAndCategoryRef>(status, _headers, result200));

        } else if (status === 404) {
            return throwException("NotFound: " + response.config.url, status, response.data, _headers, null);
        }
        else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<UpdatedEntityDtoOfintAndCategoryRef>>(new ApiResponse(status, _headers, null as any));
    }
}

export class ConsumptionLogsClient extends ApiClientBase {
    protected instance: AxiosInstance;
    protected baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, instance?: AxiosInstance) {

        super();

        this.instance = instance || axios.create();

        this.baseUrl = baseUrl ?? "http://localhost:5095/";

    }

    static operations = {

        consumptionLogsGET: "api/v1/ConsumptionLogs/{id}",
        consumptionLogsDELETE: "api/v1/ConsumptionLogs/{id}",
        consumptionLogsAll: "api/v1/ConsumptionLogs",
        consumptionLogsPOST: "api/v1/ConsumptionLogs",
        consumptionLogsPUT: "api/v1/ConsumptionLogs",
    }

    static operationParams = {

        consumptionLogsGET: {} as {
            id: ConsumptionLogRef;
        },

        consumptionLogsDELETE: {} as {
            id: ConsumptionLogRef;
        },

        consumptionLogsAll: {} as {
        },

        consumptionLogsPOST: {} as {
            body: Partial<CreateConsumptionLogRequest>;
        },

        consumptionLogsPUT: {} as {
            body: Partial<UpdateConsumptionLogRequest>;
        },
    }

    /**
     * @return OK
     */
    consumptionLogsGET(id: ConsumptionLogRef, cancelToken?: CancelToken): Promise<ApiResponse<ConsumptionLogDto>> {
        let url_ = this.baseUrl + "/api/v1/ConsumptionLogs/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace(/{id}/gi, encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.instance.request(transformedOptions_);
        }).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processConsumptionLogsGET(_response);
        });
    }

    protected processConsumptionLogsGET(response: AxiosResponse): Promise<ApiResponse<ConsumptionLogDto>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = typeof(resultData200) === "object" ? resultData200 : JSON.parse(resultData200);
            return Promise.resolve<ApiResponse<ConsumptionLogDto>>(new ApiResponse<ConsumptionLogDto>(status, _headers, result200));

        } else if (status === 404) {
            return throwException("NotFound: " + response.config.url, status, response.data, _headers, null);
        }
        else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<ConsumptionLogDto>>(new ApiResponse(status, _headers, null as any));
    }

    /**
     * @return OK
     */
    consumptionLogsDELETE(id: ConsumptionLogRef, cancelToken?: CancelToken): Promise<ApiResponse<void>> {
        let url_ = this.baseUrl + "/api/v1/ConsumptionLogs/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace(/{id}/gi, encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "DELETE",
            url: url_,
            headers: {
            },
            cancelToken
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.instance.request(transformedOptions_);
        }).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processConsumptionLogsDELETE(_response);
        });
    }

    protected processConsumptionLogsDELETE(response: AxiosResponse): Promise<ApiResponse<void>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            return Promise.resolve<ApiResponse<void>>(new ApiResponse<void>(status, _headers, null as any));

        } else if (status === 404) {
            return throwException("NotFound: " + response.config.url, status, response.data, _headers, null);
        }
        else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<void>>(new ApiResponse(status, _headers, null as any));
    }

    /**
     * @return OK
     */
    consumptionLogsAll( cancelToken?: CancelToken): Promise<ApiResponse<ConsumptionLogDto[]>> {
        let url_ = this.baseUrl + "/api/v1/ConsumptionLogs";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.instance.request(transformedOptions_);
        }).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processConsumptionLogsAll(_response);
        });
    }

    protected processConsumptionLogsAll(response: AxiosResponse): Promise<ApiResponse<ConsumptionLogDto[]>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = typeof(resultData200) === "object" ? resultData200 : JSON.parse(resultData200);
            return Promise.resolve<ApiResponse<ConsumptionLogDto[]>>(new ApiResponse<ConsumptionLogDto[]>(status, _headers, result200));

        } else if (status === 404) {
            return throwException("NotFound: " + response.config.url, status, response.data, _headers, null);
        }
        else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<ConsumptionLogDto[]>>(new ApiResponse(status, _headers, null as any));
    }

    /**
     * @return OK
     */
    consumptionLogsPOST(body: CreateConsumptionLogRequest, cancelToken?: CancelToken): Promise<ApiResponse<CreatedEntityDtoOfintAndConsumptionLogRef>> {
        let url_ = this.baseUrl + "/api/v1/ConsumptionLogs";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.instance.request(transformedOptions_);
        }).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processConsumptionLogsPOST(_response);
        });
    }

    protected processConsumptionLogsPOST(response: AxiosResponse): Promise<ApiResponse<CreatedEntityDtoOfintAndConsumptionLogRef>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = typeof(resultData200) === "object" ? resultData200 : JSON.parse(resultData200);
            return Promise.resolve<ApiResponse<CreatedEntityDtoOfintAndConsumptionLogRef>>(new ApiResponse<CreatedEntityDtoOfintAndConsumptionLogRef>(status, _headers, result200));

        } else if (status === 404) {
            return throwException("NotFound: " + response.config.url, status, response.data, _headers, null);
        }
        else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<CreatedEntityDtoOfintAndConsumptionLogRef>>(new ApiResponse(status, _headers, null as any));
    }

    /**
     * @return OK
     */
    consumptionLogsPUT(body: UpdateConsumptionLogRequest, cancelToken?: CancelToken): Promise<ApiResponse<UpdatedEntityDtoOfintAndConsumptionLogRef>> {
        let url_ = this.baseUrl + "/api/v1/ConsumptionLogs";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "PUT",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.instance.request(transformedOptions_);
        }).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processConsumptionLogsPUT(_response);
        });
    }

    protected processConsumptionLogsPUT(response: AxiosResponse): Promise<ApiResponse<UpdatedEntityDtoOfintAndConsumptionLogRef>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = typeof(resultData200) === "object" ? resultData200 : JSON.parse(resultData200);
            return Promise.resolve<ApiResponse<UpdatedEntityDtoOfintAndConsumptionLogRef>>(new ApiResponse<UpdatedEntityDtoOfintAndConsumptionLogRef>(status, _headers, result200));

        } else if (status === 404) {
            return throwException("NotFound: " + response.config.url, status, response.data, _headers, null);
        }
        else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<UpdatedEntityDtoOfintAndConsumptionLogRef>>(new ApiResponse(status, _headers, null as any));
    }
}

export class OpenFoodFactsClient extends ApiClientBase {
    protected instance: AxiosInstance;
    protected baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, instance?: AxiosInstance) {

        super();

        this.instance = instance || axios.create();

        this.baseUrl = baseUrl ?? "http://localhost:5095/";

    }

    static operations = {

        searchByBarCode: "api/v1/OpenFoodFacts/by-barcode/{barCode}",
    }

    static operationParams = {

        searchByBarCode: {} as {
            barCode: string;
        },
    }

    /**
     * @return OK
     */
    searchByBarCode(barCode: string, cancelToken?: CancelToken): Promise<ApiResponse<OpenFoodFactsProductDto[]>> {
        let url_ = this.baseUrl + "/api/v1/OpenFoodFacts/by-barcode/{barCode}";
        if (barCode === undefined || barCode === null)
            throw new Error("The parameter 'barCode' must be defined.");
        url_ = url_.replace(/{barCode}/gi, encodeURIComponent("" + barCode));
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.instance.request(transformedOptions_);
        }).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processSearchByBarCode(_response);
        });
    }

    protected processSearchByBarCode(response: AxiosResponse): Promise<ApiResponse<OpenFoodFactsProductDto[]>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = typeof(resultData200) === "object" ? resultData200 : JSON.parse(resultData200);
            return Promise.resolve<ApiResponse<OpenFoodFactsProductDto[]>>(new ApiResponse<OpenFoodFactsProductDto[]>(status, _headers, result200));

        } else if (status === 404) {
            return throwException("NotFound: " + response.config.url, status, response.data, _headers, null);
        }
        else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<OpenFoodFactsProductDto[]>>(new ApiResponse(status, _headers, null as any));
    }
}

export class ProductsClient extends ApiClientBase {
    protected instance: AxiosInstance;
    protected baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, instance?: AxiosInstance) {

        super();

        this.instance = instance || axios.create();

        this.baseUrl = baseUrl ?? "http://localhost:5095/";

    }

    static operations = {

        byBarcode: "api/v1/Products/by-barcode/{barCode}",
        productsGET: "api/v1/Products/{id}",
        productsDELETE: "api/v1/Products/{id}",
        productsAll: "api/v1/Products",
        productsPOST: "api/v1/Products",
        productsPUT: "api/v1/Products",
    }

    static operationParams = {

        byBarcode: {} as {
            barCode: string;
        },

        productsGET: {} as {
            id: ProductRef;
        },

        productsDELETE: {} as {
            id: ProductRef;
        },

        productsAll: {} as {
        },

        productsPOST: {} as {
            body: Partial<CreateProductRequest>;
        },

        productsPUT: {} as {
            body: Partial<UpdateProductRequest>;
        },
    }

    /**
     * @return OK
     */
    byBarcode(barCode: string, cancelToken?: CancelToken): Promise<ApiResponse<ProductDto[]>> {
        let url_ = this.baseUrl + "/api/v1/Products/by-barcode/{barCode}";
        if (barCode === undefined || barCode === null)
            throw new Error("The parameter 'barCode' must be defined.");
        url_ = url_.replace(/{barCode}/gi, encodeURIComponent("" + barCode));
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.instance.request(transformedOptions_);
        }).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processByBarcode(_response);
        });
    }

    protected processByBarcode(response: AxiosResponse): Promise<ApiResponse<ProductDto[]>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = typeof(resultData200) === "object" ? resultData200 : JSON.parse(resultData200);
            return Promise.resolve<ApiResponse<ProductDto[]>>(new ApiResponse<ProductDto[]>(status, _headers, result200));

        } else if (status === 404) {
            return throwException("NotFound: " + response.config.url, status, response.data, _headers, null);
        }
        else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<ProductDto[]>>(new ApiResponse(status, _headers, null as any));
    }

    /**
     * @return OK
     */
    productsGET(id: ProductRef, cancelToken?: CancelToken): Promise<ApiResponse<ProductDto>> {
        let url_ = this.baseUrl + "/api/v1/Products/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace(/{id}/gi, encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.instance.request(transformedOptions_);
        }).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processProductsGET(_response);
        });
    }

    protected processProductsGET(response: AxiosResponse): Promise<ApiResponse<ProductDto>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = typeof(resultData200) === "object" ? resultData200 : JSON.parse(resultData200);
            return Promise.resolve<ApiResponse<ProductDto>>(new ApiResponse<ProductDto>(status, _headers, result200));

        } else if (status === 404) {
            return throwException("NotFound: " + response.config.url, status, response.data, _headers, null);
        }
        else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<ProductDto>>(new ApiResponse(status, _headers, null as any));
    }

    /**
     * @return OK
     */
    productsDELETE(id: ProductRef, cancelToken?: CancelToken): Promise<ApiResponse<void>> {
        let url_ = this.baseUrl + "/api/v1/Products/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace(/{id}/gi, encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "DELETE",
            url: url_,
            headers: {
            },
            cancelToken
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.instance.request(transformedOptions_);
        }).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processProductsDELETE(_response);
        });
    }

    protected processProductsDELETE(response: AxiosResponse): Promise<ApiResponse<void>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            return Promise.resolve<ApiResponse<void>>(new ApiResponse<void>(status, _headers, null as any));

        } else if (status === 404) {
            return throwException("NotFound: " + response.config.url, status, response.data, _headers, null);
        }
        else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<void>>(new ApiResponse(status, _headers, null as any));
    }

    /**
     * @return OK
     */
    productsAll( cancelToken?: CancelToken): Promise<ApiResponse<ProductDto[]>> {
        let url_ = this.baseUrl + "/api/v1/Products";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.instance.request(transformedOptions_);
        }).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processProductsAll(_response);
        });
    }

    protected processProductsAll(response: AxiosResponse): Promise<ApiResponse<ProductDto[]>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = typeof(resultData200) === "object" ? resultData200 : JSON.parse(resultData200);
            return Promise.resolve<ApiResponse<ProductDto[]>>(new ApiResponse<ProductDto[]>(status, _headers, result200));

        } else if (status === 404) {
            return throwException("NotFound: " + response.config.url, status, response.data, _headers, null);
        }
        else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<ProductDto[]>>(new ApiResponse(status, _headers, null as any));
    }

    /**
     * @return OK
     */
    productsPOST(body: CreateProductRequest, cancelToken?: CancelToken): Promise<ApiResponse<CreatedEntityDtoOfintAndProductRef>> {
        let url_ = this.baseUrl + "/api/v1/Products";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.instance.request(transformedOptions_);
        }).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processProductsPOST(_response);
        });
    }

    protected processProductsPOST(response: AxiosResponse): Promise<ApiResponse<CreatedEntityDtoOfintAndProductRef>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = typeof(resultData200) === "object" ? resultData200 : JSON.parse(resultData200);
            return Promise.resolve<ApiResponse<CreatedEntityDtoOfintAndProductRef>>(new ApiResponse<CreatedEntityDtoOfintAndProductRef>(status, _headers, result200));

        } else if (status === 404) {
            return throwException("NotFound: " + response.config.url, status, response.data, _headers, null);
        }
        else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<CreatedEntityDtoOfintAndProductRef>>(new ApiResponse(status, _headers, null as any));
    }

    /**
     * @return OK
     */
    productsPUT(body: UpdateProductRequest, cancelToken?: CancelToken): Promise<ApiResponse<UpdatedEntityDtoOfintAndProductRef>> {
        let url_ = this.baseUrl + "/api/v1/Products";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "PUT",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.instance.request(transformedOptions_);
        }).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processProductsPUT(_response);
        });
    }

    protected processProductsPUT(response: AxiosResponse): Promise<ApiResponse<UpdatedEntityDtoOfintAndProductRef>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = typeof(resultData200) === "object" ? resultData200 : JSON.parse(resultData200);
            return Promise.resolve<ApiResponse<UpdatedEntityDtoOfintAndProductRef>>(new ApiResponse<UpdatedEntityDtoOfintAndProductRef>(status, _headers, result200));

        } else if (status === 404) {
            return throwException("NotFound: " + response.config.url, status, response.data, _headers, null);
        }
        else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<UpdatedEntityDtoOfintAndProductRef>>(new ApiResponse(status, _headers, null as any));
    }
}

export class StorageLocationsClient extends ApiClientBase {
    protected instance: AxiosInstance;
    protected baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, instance?: AxiosInstance) {

        super();

        this.instance = instance || axios.create();

        this.baseUrl = baseUrl ?? "http://localhost:5095/";

    }

    static operations = {

        storageLocationsGET: "api/v1/StorageLocations/{id}",
        storageLocationsDELETE: "api/v1/StorageLocations/{id}",
        storageLocationsAll: "api/v1/StorageLocations",
        storageLocationsPOST: "api/v1/StorageLocations",
        storageLocationsPUT: "api/v1/StorageLocations",
    }

    static operationParams = {

        storageLocationsGET: {} as {
            id: StorageLocationRef;
        },

        storageLocationsDELETE: {} as {
            id: StorageLocationRef;
        },

        storageLocationsAll: {} as {
        },

        storageLocationsPOST: {} as {
            body: Partial<CreateStorageLocationRequest>;
        },

        storageLocationsPUT: {} as {
            body: Partial<UpdateStorageLocationRequest>;
        },
    }

    /**
     * @return OK
     */
    storageLocationsGET(id: StorageLocationRef, cancelToken?: CancelToken): Promise<ApiResponse<StorageLocationDto>> {
        let url_ = this.baseUrl + "/api/v1/StorageLocations/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace(/{id}/gi, encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.instance.request(transformedOptions_);
        }).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processStorageLocationsGET(_response);
        });
    }

    protected processStorageLocationsGET(response: AxiosResponse): Promise<ApiResponse<StorageLocationDto>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = typeof(resultData200) === "object" ? resultData200 : JSON.parse(resultData200);
            return Promise.resolve<ApiResponse<StorageLocationDto>>(new ApiResponse<StorageLocationDto>(status, _headers, result200));

        } else if (status === 404) {
            return throwException("NotFound: " + response.config.url, status, response.data, _headers, null);
        }
        else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<StorageLocationDto>>(new ApiResponse(status, _headers, null as any));
    }

    /**
     * @return OK
     */
    storageLocationsDELETE(id: StorageLocationRef, cancelToken?: CancelToken): Promise<ApiResponse<void>> {
        let url_ = this.baseUrl + "/api/v1/StorageLocations/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace(/{id}/gi, encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "DELETE",
            url: url_,
            headers: {
            },
            cancelToken
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.instance.request(transformedOptions_);
        }).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processStorageLocationsDELETE(_response);
        });
    }

    protected processStorageLocationsDELETE(response: AxiosResponse): Promise<ApiResponse<void>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            return Promise.resolve<ApiResponse<void>>(new ApiResponse<void>(status, _headers, null as any));

        } else if (status === 404) {
            return throwException("NotFound: " + response.config.url, status, response.data, _headers, null);
        }
        else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<void>>(new ApiResponse(status, _headers, null as any));
    }

    /**
     * @return OK
     */
    storageLocationsAll( cancelToken?: CancelToken): Promise<ApiResponse<StorageLocationDto[]>> {
        let url_ = this.baseUrl + "/api/v1/StorageLocations";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.instance.request(transformedOptions_);
        }).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processStorageLocationsAll(_response);
        });
    }

    protected processStorageLocationsAll(response: AxiosResponse): Promise<ApiResponse<StorageLocationDto[]>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = typeof(resultData200) === "object" ? resultData200 : JSON.parse(resultData200);
            return Promise.resolve<ApiResponse<StorageLocationDto[]>>(new ApiResponse<StorageLocationDto[]>(status, _headers, result200));

        } else if (status === 404) {
            return throwException("NotFound: " + response.config.url, status, response.data, _headers, null);
        }
        else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<StorageLocationDto[]>>(new ApiResponse(status, _headers, null as any));
    }

    /**
     * @return OK
     */
    storageLocationsPOST(body: CreateStorageLocationRequest, cancelToken?: CancelToken): Promise<ApiResponse<CreatedEntityDtoOfintAndStorageLocationRef>> {
        let url_ = this.baseUrl + "/api/v1/StorageLocations";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.instance.request(transformedOptions_);
        }).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processStorageLocationsPOST(_response);
        });
    }

    protected processStorageLocationsPOST(response: AxiosResponse): Promise<ApiResponse<CreatedEntityDtoOfintAndStorageLocationRef>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = typeof(resultData200) === "object" ? resultData200 : JSON.parse(resultData200);
            return Promise.resolve<ApiResponse<CreatedEntityDtoOfintAndStorageLocationRef>>(new ApiResponse<CreatedEntityDtoOfintAndStorageLocationRef>(status, _headers, result200));

        } else if (status === 404) {
            return throwException("NotFound: " + response.config.url, status, response.data, _headers, null);
        }
        else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<CreatedEntityDtoOfintAndStorageLocationRef>>(new ApiResponse(status, _headers, null as any));
    }

    /**
     * @return OK
     */
    storageLocationsPUT(body: UpdateStorageLocationRequest, cancelToken?: CancelToken): Promise<ApiResponse<UpdatedEntityDtoOfintAndStorageLocationRef>> {
        let url_ = this.baseUrl + "/api/v1/StorageLocations";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "PUT",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.instance.request(transformedOptions_);
        }).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processStorageLocationsPUT(_response);
        });
    }

    protected processStorageLocationsPUT(response: AxiosResponse): Promise<ApiResponse<UpdatedEntityDtoOfintAndStorageLocationRef>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = typeof(resultData200) === "object" ? resultData200 : JSON.parse(resultData200);
            return Promise.resolve<ApiResponse<UpdatedEntityDtoOfintAndStorageLocationRef>>(new ApiResponse<UpdatedEntityDtoOfintAndStorageLocationRef>(status, _headers, result200));

        } else if (status === 404) {
            return throwException("NotFound: " + response.config.url, status, response.data, _headers, null);
        }
        else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<UpdatedEntityDtoOfintAndStorageLocationRef>>(new ApiResponse(status, _headers, null as any));
    }
}

export class TrackedProductsClient extends ApiClientBase {
    protected instance: AxiosInstance;
    protected baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, instance?: AxiosInstance) {

        super();

        this.instance = instance || axios.create();

        this.baseUrl = baseUrl ?? "http://localhost:5095/";

    }

    static operations = {

        trackedProductsGET: "api/v1/TrackedProducts/{id}",
        trackedProductsDELETE: "api/v1/TrackedProducts/{id}",
        trackedProductsAll: "api/v1/TrackedProducts",
        trackedProductsPOST: "api/v1/TrackedProducts",
        trackedProductsPUT: "api/v1/TrackedProducts",
    }

    static operationParams = {

        trackedProductsGET: {} as {
            id: TrackedProductRef;
        },

        trackedProductsDELETE: {} as {
            id: TrackedProductRef;
        },

        trackedProductsAll: {} as {
        },

        trackedProductsPOST: {} as {
            body: Partial<CreateTrackedProductRequest>;
        },

        trackedProductsPUT: {} as {
            body: Partial<UpdateTrackedProductRequest>;
        },
    }

    /**
     * @return OK
     */
    trackedProductsGET(id: TrackedProductRef, cancelToken?: CancelToken): Promise<ApiResponse<TrackedProductDto>> {
        let url_ = this.baseUrl + "/api/v1/TrackedProducts/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace(/{id}/gi, encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.instance.request(transformedOptions_);
        }).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processTrackedProductsGET(_response);
        });
    }

    protected processTrackedProductsGET(response: AxiosResponse): Promise<ApiResponse<TrackedProductDto>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = typeof(resultData200) === "object" ? resultData200 : JSON.parse(resultData200);
            return Promise.resolve<ApiResponse<TrackedProductDto>>(new ApiResponse<TrackedProductDto>(status, _headers, result200));

        } else if (status === 404) {
            return throwException("NotFound: " + response.config.url, status, response.data, _headers, null);
        }
        else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<TrackedProductDto>>(new ApiResponse(status, _headers, null as any));
    }

    /**
     * @return OK
     */
    trackedProductsDELETE(id: TrackedProductRef, cancelToken?: CancelToken): Promise<ApiResponse<void>> {
        let url_ = this.baseUrl + "/api/v1/TrackedProducts/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace(/{id}/gi, encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "DELETE",
            url: url_,
            headers: {
            },
            cancelToken
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.instance.request(transformedOptions_);
        }).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processTrackedProductsDELETE(_response);
        });
    }

    protected processTrackedProductsDELETE(response: AxiosResponse): Promise<ApiResponse<void>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            return Promise.resolve<ApiResponse<void>>(new ApiResponse<void>(status, _headers, null as any));

        } else if (status === 404) {
            return throwException("NotFound: " + response.config.url, status, response.data, _headers, null);
        }
        else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<void>>(new ApiResponse(status, _headers, null as any));
    }

    /**
     * @return OK
     */
    trackedProductsAll( cancelToken?: CancelToken): Promise<ApiResponse<TrackedProductDto[]>> {
        let url_ = this.baseUrl + "/api/v1/TrackedProducts";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.instance.request(transformedOptions_);
        }).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processTrackedProductsAll(_response);
        });
    }

    protected processTrackedProductsAll(response: AxiosResponse): Promise<ApiResponse<TrackedProductDto[]>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = typeof(resultData200) === "object" ? resultData200 : JSON.parse(resultData200);
            return Promise.resolve<ApiResponse<TrackedProductDto[]>>(new ApiResponse<TrackedProductDto[]>(status, _headers, result200));

        } else if (status === 404) {
            return throwException("NotFound: " + response.config.url, status, response.data, _headers, null);
        }
        else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<TrackedProductDto[]>>(new ApiResponse(status, _headers, null as any));
    }

    /**
     * @return OK
     */
    trackedProductsPOST(body: CreateTrackedProductRequest, cancelToken?: CancelToken): Promise<ApiResponse<CreatedEntityDtoOfintAndTrackedProductRef>> {
        let url_ = this.baseUrl + "/api/v1/TrackedProducts";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.instance.request(transformedOptions_);
        }).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processTrackedProductsPOST(_response);
        });
    }

    protected processTrackedProductsPOST(response: AxiosResponse): Promise<ApiResponse<CreatedEntityDtoOfintAndTrackedProductRef>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = typeof(resultData200) === "object" ? resultData200 : JSON.parse(resultData200);
            return Promise.resolve<ApiResponse<CreatedEntityDtoOfintAndTrackedProductRef>>(new ApiResponse<CreatedEntityDtoOfintAndTrackedProductRef>(status, _headers, result200));

        } else if (status === 404) {
            return throwException("NotFound: " + response.config.url, status, response.data, _headers, null);
        }
        else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<CreatedEntityDtoOfintAndTrackedProductRef>>(new ApiResponse(status, _headers, null as any));
    }

    /**
     * @return OK
     */
    trackedProductsPUT(body: UpdateTrackedProductRequest, cancelToken?: CancelToken): Promise<ApiResponse<UpdatedEntityDtoOfintAndTrackedProductRef>> {
        let url_ = this.baseUrl + "/api/v1/TrackedProducts";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "PUT",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.instance.request(transformedOptions_);
        }).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processTrackedProductsPUT(_response);
        });
    }

    protected processTrackedProductsPUT(response: AxiosResponse): Promise<ApiResponse<UpdatedEntityDtoOfintAndTrackedProductRef>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = typeof(resultData200) === "object" ? resultData200 : JSON.parse(resultData200);
            return Promise.resolve<ApiResponse<UpdatedEntityDtoOfintAndTrackedProductRef>>(new ApiResponse<UpdatedEntityDtoOfintAndTrackedProductRef>(status, _headers, result200));

        } else if (status === 404) {
            return throwException("NotFound: " + response.config.url, status, response.data, _headers, null);
        }
        else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<UpdatedEntityDtoOfintAndTrackedProductRef>>(new ApiResponse(status, _headers, null as any));
    }
}

export interface CategoryDto {
    id: CategoryRef;
    name: string;
    description: string | undefined;
    iconName: string;
    dateCreated: number;
    lastModified: number;
}

export interface ConsumptionLogDto {
    id: ConsumptionLogRef;
    productId: ProductRef;
    quantity: number;
    reason: string | undefined;
    dateCreated: number;
    lastModified: number;
}

export interface CreateCategoryRequest {
    name: string;
    description: string | undefined;
    iconName: string;
}

export interface CreateConsumptionLogRequest {
    productId: ProductRef;
    quantity: number;
    reason: string | undefined;
}

export interface CreatedEntityDtoOfintAndCategoryRef {
    entityId: CategoryRef;
    lastModified: number;
}

export interface CreatedEntityDtoOfintAndConsumptionLogRef {
    entityId: ConsumptionLogRef;
    lastModified: number;
}

export interface CreatedEntityDtoOfintAndProductRef {
    entityId: ProductRef;
    lastModified: number;
}

export interface CreatedEntityDtoOfintAndStorageLocationRef {
    entityId: StorageLocationRef;
    lastModified: number;
}

export interface CreatedEntityDtoOfintAndTrackedProductRef {
    entityId: TrackedProductRef;
    lastModified: number;
}

export interface CreateProductRequest {
    name: string;
    description: string | undefined;
    categoryId: CategoryRef;
    manufacturer: string | undefined;
    barCode: string | undefined;
    imageUrl: string | undefined;
    imageSmallUrl: string | undefined;
    unitOfMeasure: number;
    minimumStockLevel: number;
}

export interface CreateStorageLocationRequest {
    name: string;
}

export interface CreateTrackedProductRequest {
    productId: ProductRef;
    storageLocationId: StorageLocationRef;
    expirationDate: number | undefined;
    quantity: number;
    notes: string | undefined;
}

export interface OpenFoodFactsProductDto {
    code: string;
    productName: string | undefined;
    brands: string | undefined;
    categories: string | undefined;
    quantity: number | undefined;
    unitOfMeasure: number | undefined;
    imageUrl: string | undefined;
    imageSmallUrl: string | undefined;
}

export interface ProductDto {
    id: ProductRef;
    name: string;
    description: string | undefined;
    categoryId: CategoryRef;
    manufacturer: string | undefined;
    barCode: string | undefined;
    imageUrl: string | undefined;
    imageSmallUrl: string | undefined;
    unitOfMeasure: number;
    minimumStockLevel: number;
    trackedProductsCount: number;
    dateCreated: number;
    lastModified: number;
}

export interface StorageLocationDto {
    id: StorageLocationRef;
    name: string;
    dateCreated: number;
    lastModified: number;
}

export interface TrackedProductDto {
    id: TrackedProductRef;
    productId: ProductRef;
    storageLocationId: StorageLocationRef;
    expirationDate: number | undefined;
    quantity: number;
    notes: string | undefined;
    dateCreated: number;
    lastModified: number;
}

export interface UpdateCategoryRequest {
    id: CategoryRef;
    lastModified: number;
    name: string;
    description: string | undefined;
    iconName: string;
}

export interface UpdateConsumptionLogRequest {
    id: ConsumptionLogRef;
    lastModified: number;
    productId: ProductRef;
    quantity: number;
    reason: string | undefined;
}

export interface UpdatedEntityDtoOfintAndCategoryRef {
    entityId: CategoryRef;
    lastModified: number;
}

export interface UpdatedEntityDtoOfintAndConsumptionLogRef {
    entityId: ConsumptionLogRef;
    lastModified: number;
}

export interface UpdatedEntityDtoOfintAndProductRef {
    entityId: ProductRef;
    lastModified: number;
}

export interface UpdatedEntityDtoOfintAndStorageLocationRef {
    entityId: StorageLocationRef;
    lastModified: number;
}

export interface UpdatedEntityDtoOfintAndTrackedProductRef {
    entityId: TrackedProductRef;
    lastModified: number;
}

export interface UpdateProductRequest {
    id: ProductRef;
    lastModified: number;
    name: string;
    description: string | undefined;
    categoryId: CategoryRef;
    manufacturer: string | undefined;
    barCode: string | undefined;
    imageUrl: string | undefined;
    imageSmallUrl: string | undefined;
    unitOfMeasure: number;
    minimumStockLevel: number;
}

export interface UpdateStorageLocationRequest {
    id: StorageLocationRef;
    lastModified: number;
    name: string;
}

export interface UpdateTrackedProductRequest {
    id: TrackedProductRef;
    lastModified: number;
    productId: ProductRef;
    storageLocationId: StorageLocationRef;
    expirationDate: number | undefined;
    quantity: number;
    notes: string | undefined;
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}

function isAxiosError(obj: any): obj is AxiosError {
    return obj && obj.isAxiosError === true;
}