<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <ReferenceAtomData>true</ReferenceAtomData>
    <ReferenceAtomDataEf>true</ReferenceAtomDataEf>
    <ReferenceAtomInfrastructure>true</ReferenceAtomInfrastructure>
    <ReferenceAtomWeb>true</ReferenceAtomWeb>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PrepperBox.WebApi\PrepperBox.WebApi.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
  </ItemGroup>
</Project>
